apiVersion: v1
kind: Pod
metadata:
  name: first-demo-app
  namespace: demo-apps
  labels:
    app: first-demo-app
spec:
  containers:
    - name: first-demo-app
      image: busybox
      command: ['sh', '-c', 'while true; do echo Hello Kubernetes from first-demo-app; sleep 10; done']
